[package]
name = "object_store"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
axum-streams = "0.21.0"
thiserror = "2.0.12"
tokio = {version = "1.44.2", features = ["full"]}
futures = "0.3.31"
bytes = "1.10.1"
tokio-stream = "0.1.17"
futures-util = "0.3.31"
